version: "3.9"
services:
  postgres:
    image: postgres:latest
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - monorepo:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=redis_new
    volumes:
      - monorepo:/var/db/redis/data

volumes:
  monorepo:
    driver: local
    name: monorepo