// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AtomActionMessage: typeof import('./../../../packages/vue-design-system/components/atom/action-message.vue')['default']
    AtomButton: typeof import('./../../../packages/vue-design-system/components/atom/Button.vue')['default']
    AtomHDialogBg: typeof import('./../../../packages/vue-design-system/components/atom/h-dialog-bg.vue')['default']
    AtomHOverlay: typeof import('./../../../packages/vue-design-system/components/atom/h-overlay.vue')['default']
    AtomSectionTitle: typeof import('./../../../packages/vue-design-system/components/atom/section-title.vue')['default']
    ExploreContainer: typeof import('./../../../packages/vue-design-system/components/ExploreContainer.vue')['default']
    FormCheckboxWithValidation: typeof import('./../../../packages/vue-design-system/components/form/checkbox-with-validation.vue')['default']
    FormInputWithValidation: typeof import('./../../../packages/vue-design-system/components/form/input-with-validation.vue')['default']
    FormSection: typeof import('./../../../packages/vue-design-system/components/form/section.vue')['default']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonBadge: typeof import('@ionic/vue')['IonBadge']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonItemDivider: typeof import('@ionic/vue')['IonItemDivider']
    IonItemGroup: typeof import('@ionic/vue')['IonItemGroup']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonSlide: typeof import('@ionic/vue')['IonSlide']
    IonSlides: typeof import('@ionic/vue')['IonSlides']
    IonSpinner: typeof import('@ionic/vue')['IonSpinner']
    IonTabBar: typeof import('@ionic/vue')['IonTabBar']
    IonTabButton: typeof import('@ionic/vue')['IonTabButton']
    IonTabs: typeof import('@ionic/vue')['IonTabs']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToggle: typeof import('@ionic/vue')['IonToggle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    PaymentModal: typeof import('./components/PaymentModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleHead: typeof import('./../../../packages/vue-design-system/components/TitleHead.vue')['default']
    UnoIcon: typeof import('./../../../packages/vue-design-system/components/UnoIcon.vue')['default']
  }
}
