#!/bin/bash
set -e
set -u

echo "EXTENSIONS CREATING"

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pgcrypto";
EOSQL

echo "EXTENSIONS CREATED SUCCESSFULLY"
