// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AtomActionMessage: typeof import('./../../../packages/vue-design-system/components/atom/action-message.vue')['default']
    AtomButton: typeof import('./../../../packages/vue-design-system/components/atom/Button.vue')['default']
    AtomHDialogBg: typeof import('./../../../packages/vue-design-system/components/atom/h-dialog-bg.vue')['default']
    AtomHOverlay: typeof import('./../../../packages/vue-design-system/components/atom/h-overlay.vue')['default']
    AtomSectionTitle: typeof import('./../../../packages/vue-design-system/components/atom/section-title.vue')['default']
    ExploreContainer: typeof import('./../../../packages/vue-design-system/components/ExploreContainer.vue')['default']
    FormCheckboxWithValidation: typeof import('./../../../packages/vue-design-system/components/form/checkbox-with-validation.vue')['default']
    FormInputWithValidation: typeof import('./../../../packages/vue-design-system/components/form/input-with-validation.vue')['default']
    FormSection: typeof import('./../../../packages/vue-design-system/components/form/section.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MainPanel: typeof import('./components/MainPanel.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    OrgLeftSidebar: typeof import('./components/org/left-sidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidePanel: typeof import('./components/SidePanel.vue')['default']
    TemLoadData: typeof import('./components/tem/LoadData.vue')['default']
    TitleHead: typeof import('./../../../packages/vue-design-system/components/TitleHead.vue')['default']
    UnoIcon: typeof import('./../../../packages/vue-design-system/components/UnoIcon.vue')['default']
  }
}
